const palette = {
  lavender: "#B8A9E8",
  lavenderLight: "#D4C8F5",
  lavenderDark: "#8B7AC9",
  peach: "#F0A896",
  peachLight: "#FAD5CB",
  coral: "#E8806A",
  rose: "#E8A0A0",
  offWhite: "#FAFAF8",
  softGray: "#F2F0F5",
  midGray: "#C8C5D0",
  darkGray: "#6B6878",
  charcoal: "#1A1825",
  charcoalMid: "#252235",
  charcoalLight: "#302D44",
  cardBg: "#2B2840",
  white: "#FFFFFF",
  black: "#000000",
  success: "#7CC98A",
  warning: "#F0C86A",
  danger: "#E87070",
};

export const Colors = {
  light: {
    background: palette.offWhite,
    card: palette.white,
    cardBorder: "#ECEAF2",
    text: "#1A1825",
    textSecondary: palette.darkGray,
    textMuted: palette.midGray,
    primary: palette.lavenderDark,
    primaryLight: palette.lavenderLight,
    accent: palette.coral,
    accentLight: palette.peachLight,
    tabBar: palette.white,
    tabBarActive: palette.lavenderDark,
    tabBarInactive: palette.midGray,
    inputBg: palette.softGray,
    inputBorder: "#E0DDE8",
    separator: "#ECEAF2",
    success: palette.success,
    warning: palette.warning,
    danger: palette.danger,
    tint: palette.lavenderDark,
    tabIconDefault: palette.midGray,
    tabIconSelected: palette.lavenderDark,
  },
  dark: {
    background: palette.charcoal,
    card: palette.charcoalMid,
    cardBorder: palette.charcoalLight,
    text: "#F0EEF8",
    textSecondary: "#A8A5B8",
    textMuted: "#605D72",
    primary: palette.lavender,
    primaryLight: palette.lavenderDark,
    accent: palette.peach,
    accentLight: "#4A3840",
    tabBar: palette.charcoalMid,
    tabBarActive: palette.lavender,
    tabBarInactive: "#605D72",
    inputBg: palette.charcoalLight,
    inputBorder: "#3D3A52",
    separator: "#302D44",
    success: palette.success,
    warning: palette.warning,
    danger: palette.danger,
    tint: palette.lavender,
    tabIconDefault: "#605D72",
    tabIconSelected: palette.lavender,
  },
};

export default Colors;
